#
# fortune-service 
#
#spring:
#  datasource:
#    url: jdbc:h2:file:/tmp/data/demo-${random:int}
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
spring:
  profiles:
    active:
    - down
  application:
    name: fortune-service
  session:
    store-type: jdbc
  datasource:
    url: "jdbc:h2:mem:testdb"
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
fortunes:
  messages:
  - You will get a surprising opportunity
  - When it rains, an umbrella will be near
  - The way of Spring is right for you
  - Things will only get better from here
  - Dockerizing apps is the way of the future
  - A mysterious stranger presents a great oportunity
  - Eclipse is awesome!
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: always
